//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace psBackEnd.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class drink
    {
        public int drinkID { get; set; }
        public Nullable<int> haveDiscount { get; set; }
        public Nullable<System.DateTime> startDiscount { get; set; }
        public Nullable<System.DateTime> endDiscount { get; set; }
        public Nullable<decimal> wasPrice { get; set; }
        public Nullable<decimal> priceAfterDiscount { get; set; }
        public Nullable<int> paymentID { get; set; }
        public Nullable<int> reservationID { get; set; }
        public Nullable<int> drinkNameID { get; set; }
    
        public virtual drinksName drinksName { get; set; }
        public virtual payment payment { get; set; }
    }
}
