//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace psBackEnd.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class payment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public payment()
        {
            this.drinks = new HashSet<drink>();
        }
    
        public int paymentID { get; set; }
        public Nullable<int> customerID { get; set; }
        public Nullable<System.DateTime> startTime { get; set; }
        public Nullable<System.DateTime> endTime { get; set; }
        public Nullable<int> adminID { get; set; }
        public Nullable<int> gameID { get; set; }
        public Nullable<int> deviceID { get; set; }
        public Nullable<decimal> amount { get; set; }
        public Nullable<int> haveRemeningAmount { get; set; }
        public Nullable<int> haveDiscount { get; set; }
        public Nullable<decimal> amountAfterDiscount { get; set; }
        public Nullable<decimal> amountBeforeDiscount { get; set; }
        public Nullable<int> reviewDiscountFromAdmin { get; set; }
        public Nullable<decimal> wasAmount { get; set; }
        public Nullable<decimal> payed { get; set; }
        public Nullable<decimal> RemeningAmount { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<int> finished { get; set; }
        public Nullable<int> singleOrMulti { get; set; }
    
        public virtual admin admin { get; set; }
        public virtual customer customer { get; set; }
        public virtual device device { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<drink> drinks { get; set; }
        public virtual game game { get; set; }
    }
}
