//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace psBackEnd.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class playHourPrice
    {
        public int playHourePriceID { get; set; }
        public Nullable<decimal> hourPlaysSingle { get; set; }
        public Nullable<decimal> hourPlayMulti { get; set; }
    }
}
