//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace psBackEnd.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class reservation
    {
        public int reservationID { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<System.DateTime> startTime { get; set; }
        public Nullable<System.DateTime> endTime { get; set; }
        public Nullable<int> adminID { get; set; }
        public Nullable<int> gameID { get; set; }
        public Nullable<int> deviceID { get; set; }
        public Nullable<int> customerID { get; set; }
        public Nullable<int> start { get; set; }
        public Nullable<int> singelOrMulti { get; set; }
    
        public virtual customer customer { get; set; }
        public virtual device device { get; set; }
    }
}
